spring:
  profiles:
    active: server
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging.level:
  com:
    amazonaws:
      util:
        EC2MetadataUtils: error
  org.hibernate.SQL: debug

#jwt:
#  key: ${JWT_SECRET_KEY}

cloud:
  aws:
#    credentials:
#      access-key: ${s3_access_key}
#      secret-key: ${s3_secret_key}
#    region:
#      static: ${s3_region}
#    s3:
#      bucket: ${s3_bucket}
    stack:
      auto: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    #    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

---
spring:
  config:
    activate:
      on-profile: server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${MYSQL_URL}
#    username: ${MYSQL_USERNAME}
#    password: ${MYSQL_PASSWORD}